<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>main</groupId>
    <artifactId>CBL</artifactId>
    <version>0.0</version>
    <packaging>jar</packaging>
    <build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>3.6.0</version>

				<configuration>
					<!-- The Checkstyle configuration file (2IP90_checks.xml)
						 must be located in the root directory of your Maven project
						 (the same directory as pom.xml). -->
					<configLocation>2IP90_checks.xml</configLocation>
					<failOnViolation>false</failOnViolation>
					<failsOnError>true</failsOnError>
					<includeTestSourceDirectory>true</includeTestSourceDirectory>
					<violationSeverity>warning</violationSeverity>
				</configuration>

				<dependencies>
					<dependency>
						<groupId>com.puppycrawl.tools</groupId>
						<artifactId>checkstyle</artifactId>
						<version>13.7.0</version>
					</dependency>
				</dependencies>

				<executions>
					<execution>
						<id>validate</id>
						<phase>validate</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>

			</plugin>
		</plugins>
	</build>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>26</maven.compiler.release>
        <exec.mainClass>CBL</exec.mainClass>
    </properties>
</project>